import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createFractalPathCache} from '../fractal-path.js';
import {setup} from './life-challenge-harness.js';
// Independent exact integer recurrence plus Float32 model storage.
function oracle(count,seed=14,jump=50){let rng=BigInt(seed),x=0,y=-1;const p=new Float32Array(count*2),v=[[0,-1],[-Math.sqrt(3)/2,.5],[Math.sqrt(3)/2,.5]];for(let i=0;i<count;i++){rng=(1664525n*rng+1013904223n)%4294967296n;const [a,b]=v[Number(rng*3n/4294967296n)];x+=(a-x)*(jump/100);y+=(b-y)*(jump/100);p[i*2]=x;p[i*2+1]=y;}return p;}
const expected=(p,n,s,x,y)=>Array.from({length:n},(_,i)=>[x+p[i*2]*s,y+p[i*2+1]*s,1.3,1.3]);
function recording(){const work={constructed:0,rects:0};class Path{constructor(){work.constructed++;this.rectangles=[];}rect(...args){work.rects++;this.rectangles.push(args);}}return {Path,work};}
const click=(h,id)=>h.el(id).handlers.click();
const input=(h,id,value)=>h.el(id).handlers.input({target:{value:String(value)}});
const seek=(h,n)=>{h.el('fractal-count').value=String(n);click(h,'fractal-seek');};
async function cached(search='?experiment=fractal',motion=true,context=true){const {Path,work}=recording(),old=Object.getOwnPropertyDescriptor(globalThis,'Path2D');try{globalThis.Path2D=Path;return {h:await setup(search,'#canvas',motion,1,context),work};}finally{if(old)Object.defineProperty(globalThis,'Path2D',old);else delete globalThis.Path2D;}}
const samples=h=>h.drawing().find(c=>c[0]==='fill'&&c[1]?.rectangles)?.[1].rectangles;
const expanded=h=>h.drawing().flatMap(c=>c[0]==='fill'&&c[1]?.rectangles?[...c[1].rectangles.map(r=>['rect',...r]),['fill']]:[c]);
function check(h,n=300,seed=14,jump=50){assert.ok(Array.isArray(samples(h)),'native sample path must be painted');const {width:w,height:v}=h.el('canvas').getBoundingClientRect(),s=Math.min(w/2.1,v/1.85);assert.deepEqual(samples(h),expected(oracle(n,seed,jump),n,s,w/2,v/2+s*.25));assert.equal(h.el('metrics').textContent,`${n} 个点 · 前进 ${jump}% · 种子 ${seed}`);}
const readings=h=>['metrics','fractal-gap-reading','fractal-choice-reading','fractal-jump-reading','observation-a','observation-b','observation-c','notes-text'].map(id=>h.el(id).value||h.el(id).textContent);

test('append-only growth constructs 12000 sample rectangles rather than 725700 prefix rectangles',()=>{const {Path,work}=recording(),get=createFractalPathCache(Path),p=oracle(12000),state={points:p,count:0};let previous,total=0;for(let n=300;n<=12000;n+=100){state.count=n;const path=get(state,200,300,250);if(previous)assert.equal(path,previous);previous=path;total+=n;assert.equal(get(state,200,300,250),path);}assert.equal(total,725700);assert.deepEqual(work,{constructed:1,rects:12000});assert.deepEqual(previous.rectangles,expected(p,12000,200,300,250));assert.deepEqual(p,oracle(12000));});

test('all supported jump ratios and representative seeds match independent Float32 geometry',()=>{const {Path}=recording(),get=createFractalPathCache(Path);for(let jump=35;jump<=70;jump++)for(const seed of [1,14,99]){const points=oracle(1000,seed,jump),state={points,count:0};for(const n of [0,1,300,731,1000]){state.count=n;assert.deepEqual(get(state,151.125,199.25,123.875).rectangles,expected(points,n,151.125,199.25,123.875));}}});

test('model or buffer replacement, rewind and every CSS projection component rebuild the sole retained path',()=>{const {Path,work}=recording(),get=createFractalPathCache(Path),points=oracle(1000),state={points,count:1000};let path=get(state,200,300,250);state.count=731;let next=get(state,200,300,250);assert.notEqual(next,path);assert.equal(next.rectangles.length,731);path=next;state.count=732;assert.equal(get(state,200,300,250),path);assert.equal(path.rectangles.length,732);for(const [s,x,y] of [[201,300,250],[201,301,250],[201,301,251],[-1,0,0],[0,0,0]]){next=get(state,s,x,y);assert.notEqual(next,path);assert.deepEqual(next.rectangles,expected(points,732,s,x,y));path=next;}state.points=oracle(1000,15,38);next=get(state,0,0,0);assert.notEqual(next,path);assert.equal(next.rectangles.length,732);assert.notEqual(get({...state},0,0,0),next);const before=work.constructed;get(state,0,0,0);assert.equal(work.constructed,before+1);});

test('missing or failed optional Path2D falls back without repeated allocation or partial path reuse',()=>{const state={points:oracle(300),count:300};assert.equal(createFractalPathCache(null)(state,1,0,0),null);let attempts=0;class Broken{constructor(){attempts++;throw Error('allocation');}}const get=createFractalPathCache(Broken);assert.equal(get(state,1,0,0),null);assert.equal(get(state,2,0,0),null);assert.equal(attempts,1);let rects=0;class Partial{rect(){if(++rects===3)throw Error('allocation');}}const partial=createFractalPathCache(Partial);assert.equal(partial(state,1,0,0),null);assert.equal(partial(state,1,0,0),null);assert.equal(rects,3);assert.deepEqual(state.points,oracle(300));});

test('120 paused cap redraws avoid 1440000 rectangle constructions and keep drawing and readings unchanged',async()=>{const {h,work}=await cached('?experiment=fractal&seed=14&jump=50&at=v1,12000'),before={...work},drawing=expanded(h),text=readings(h),message=h.el('announcement').textContent;for(let i=0;i<120;i++)h.resize(600,414);assert.deepEqual(work,before);assert.deepEqual(expanded(h),drawing);assert.deepEqual(readings(h),text);assert.equal(h.el('announcement').textContent,message);check(h,12000);});

test('cached and ordinary fallback retain every sample rectangle and the complete guide/marker paint order',async()=>{for(const [n,seed,jump,w,v] of [[300,14,50,600,414],[731,23,38,767,317.9375],[12000,99,65,259,240],[1000,15,35,171,240]]){const search=`?experiment=fractal&seed=${seed}&jump=${jump}&at=v1,${n}`,fallback=await setup(search);fallback.resize(w,v);const drawing=fallback.drawing(),text=readings(fallback);const {h}=await cached(search);h.resize(w,v);assert.deepEqual(expanded(h),drawing);assert.deepEqual(readings(h),text);check(h,n,seed,jump);}});

test('one new point appends once while focus, density and recovered context reuse CSS geometry',async()=>{const {h,work}=await cached(),initial=work.rects;click(h,'fractal-forward');assert.equal(work.rects-initial,1);check(h,301);const before={...work},text=readings(h),drawing=expanded(h);h.el('canvas').handlers.focus();h.el('canvas').handlers.blur();for(const dpr of [1.25,2,3,1])h.setDpr(dpr);h.loseContext();h.restoreContext();h.setVisible(false);h.setVisible(true);h.setHidden(true);h.setHidden(false);assert.deepEqual(work,before);assert.deepEqual(readings(h),text);assert.deepEqual(expanded(h),drawing);for(const [w,v] of [[259,240],[455.5,281.75],[767,317.9375],[600,414]]){const old=work.rects;h.resize(w,v);assert.equal(work.rects-old,301);check(h,301);const unchanged={...work};h.resize(w,v);assert.deepEqual(work,unchanged);}});

test('running append cadence, visibility gates, motion preference, cap and intentional batch repeat stay unchanged',async()=>{const {h,work}=await cached('?experiment=fractal',false),before=work.rects,message=h.el('announcement').textContent;h.tick(0);h.tick(50);h.tick(100);assert.equal(work.rects-before,100);check(h,400);h.setVisible(false);assert.equal(h.frames.size,0);h.setVisible(true);h.tick(90000);check(h,400);h.tick(90050);h.tick(90100);check(h,500);assert.equal(h.el('announcement').textContent,message);h.motion.change({matches:true});assert.equal(h.frames.size,0);h.motion.change({matches:false});assert.equal(h.frames.size,0);for(let i=0;i<3;i++)click(h,'step');check(h,800);let prevented=false;h.el('step').handlers.keydown({key:'Enter',repeat:true,preventDefault(){prevented=true;}});assert.equal(prevented,false);seek(h,11900);click(h,'pause');const cap=work.rects;h.tick(0);h.tick(50);h.tick(100);assert.equal(work.rects-cap,100);check(h,12000);assert.equal(h.frames.size,0);assert.equal(h.el('pause').getAttribute('aria-disabled'),'true');});

test('replay, saved return/undo, retained worlds, parameters, presets and history cannot retain stale samples',async()=>{const {h}=await cached('?experiment=fractal&seed=23&jump=38&at=v1,731');check(h,731,23,38);const original=expanded(h);await click(h,'share');const saved=h.el('share-link').value;seek(h,1000);check(h,1000,23,38);const later=expanded(h);click(h,'fractal-back');check(h,999,23,38);click(h,'fractal-forward');assert.deepEqual(expanded(h),later);click(h,'observation-return');assert.deepEqual(expanded(h),original);click(h,'observation-undo');assert.deepEqual(expanded(h),later);assert.equal(h.el('share-link').value,saved);for(const mode of ['life','wave','orbit','walk']){click(h,'tab-'+mode);click(h,'tab-fractal');assert.deepEqual(expanded(h),later);}input(h,'seed',99);check(h,300,99,38);input(h,'jump',65);check(h,300,99,65);h.el('preset-select').handlers.change({target:{value:'half'}});click(h,'load-preset');check(h,300,99,50);h.navigate(saved);check(h,731,23,38);click(h,'reset');check(h,300,23,38);});

test('invalid and composing targets keep the cache while exact targets and cap rewind follow their original rules',async()=>{const {h,work}=await cached(),before={...work},drawing=expanded(h);for(const raw of ['', '299','12001','3.5','NaN']){h.el('fractal-count').value=raw;click(h,'fractal-seek');assert.equal(h.el('fractal-count').getAttribute('aria-invalid'),'true');assert.deepEqual(work,before);assert.deepEqual(expanded(h),drawing);}h.el('fractal-count').value='７３１';h.el('fractal-count').handlers.keydown({key:'Enter',preventDefault(){}});check(h,731);assert.equal(h.el('fractal-count').value,'731');for(const extra of [{repeat:true},{isComposing:true},{keyCode:229},{ctrlKey:true},{metaKey:true},{shiftKey:true},{altKey:true}]){h.el('fractal-count').value='1000';h.el('fractal-count').handlers.keydown({key:'Enter',preventDefault(){},...extra});check(h,731);}seek(h,12000);click(h,'fractal-back');check(h,11999);click(h,'fractal-forward');check(h,12000);const cap={...work};click(h,'step');click(h,'fractal-forward');assert.deepEqual(work,cap);});

test('discoveries and canvas capture requests retain the same evidence and geometry',async()=>{const {h}=await cached();click(h,'mission-start');click(h,'fractal-1000');click(h,'mission-check');input(h,'seed',15);click(h,'fractal-1000');click(h,'mission-check');assert.equal(h.el('notes-count').textContent,'1 / 5');check(h,1000,15);const notes=h.el('notes-text').value,drawing=expanded(h);let captures=0;h.el('canvas').toBlob=()=>{captures++;};click(h,'save');assert.equal(captures,1);assert.deepEqual(expanded(h),drawing);assert.equal(h.el('notes-text').value,notes);});

test('text-only startup defers native paths and allocation failure keeps the ordinary drawing route',async()=>{const {h,work}=await cached('?experiment=fractal&at=v1,731',true,false);assert.equal(work.rects,0);seek(h,1000);assert.equal(work.rects,0);assert.match(h.el('metrics').textContent,/1000 个点/);h.setContextReady(true);click(h,'canvas-retry');check(h,1000);assert.equal(work.rects,1000);const old=Object.getOwnPropertyDescriptor(globalThis,'Path2D');let attempts=0;try{globalThis.Path2D=class{constructor(){attempts++;throw Error('optional allocation');}};const fallback=await setup('?experiment=fractal&at=v1,731');assert.equal(fallback.drawing().filter(c=>c[0]==='rect').length,731);seek(fallback,1000);assert.equal(fallback.drawing().filter(c=>c[0]==='rect').length,1000);assert.equal(attempts,1);}finally{if(old)Object.defineProperty(globalThis,'Path2D',old);else delete globalThis.Path2D;}});

test('an append allocation failure paints the complete legacy path and keeps advancing correctly',async()=>{const old=Object.getOwnPropertyDescriptor(globalThis,'Path2D');let builds=0,rects=0;class Partial{constructor(){builds++;this.rectangles=[];}rect(...args){if(++rects===301)throw Error('append allocation');this.rectangles.push(args);}}try{globalThis.Path2D=Partial;const h=await setup('?experiment=fractal');assert.equal(samples(h).length,300);click(h,'fractal-forward');for(const n of [301,302]){if(n===302)click(h,'fractal-forward');assert.equal(samples(h),undefined);const s=414/1.85;assert.deepEqual(h.drawing().filter(c=>c[0]==='rect').map(c=>c.slice(1)),expected(oracle(n),n,s,300,207+s*.25));assert.equal(h.el('metrics').textContent,`${n} 个点 · 前进 50% · 种子 14`);}assert.equal(builds,1);assert.equal(rects,301);}finally{if(old)Object.defineProperty(globalThis,'Path2D',old);else delete globalThis.Path2D;}});

test('cache-version wiring adds no model mutation, storage or scheduling',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),source=readFileSync(new URL('../fractal-path.js',import.meta.url),'utf8');assert.match(html,/app\.js\?[^"\n]*&amp;fractal-path=append-once-1/);assert.doesNotMatch(source,/localStorage|sessionStorage|fetch\(|requestAnimationFrame|setTimeout|\.rng|addFractalPoints/);});
