import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup} from './life-challenge-harness.js';
const click=(h,id)=>h.el(id).handlers.click();
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ≈ ${b}`);
const scale=h=>h.drawing().find(c=>c[0]==='scale')?.[1];
function position(h,x,y){for(const [axis,value] of [['x',x],['y',y]]){const el=h.el('orbit-target-'+axis);el.value=String(value);el.handlers.input();}click(h,'orbit-position-apply');}
function geometry(h){const s=scale(h),r=h.el('canvas').getBoundingClientRect(),commands=h.drawing();const rect=c=>c&&({x:r.width/2+c[1]*s,y:r.height/2+c[2]*s,w:c[3]*s,h:c[4]*s});return {s,r,commands,square:rect(commands.find(c=>c[0]==='strokeRect')),legend:rect(commands.find(c=>c[0]==='fillRect'&&Math.abs(c[3]*s-196)<1e-8&&Math.abs(c[4]*s-23)<1e-8))};}
const overlaps=(a,b,p=.75)=>a.x+a.w+p>=b.x&&a.x-p<=b.x+b.w&&a.y+a.h+p>=b.y&&a.y-p<=b.y+b.h;
// Scalar softened integration independent of the production preview and stepper.
function endpoint(x,y,gravity=80,speed=100){const r=Math.hypot(x,y),v=Math.sqrt(gravity*1000/r)*speed/100;let vx=-y/r*v,vy=x/r*v;for(let i=0;i<1000;i++){const d=Math.max(Math.hypot(x,y),18);vx-=gravity*1000*x/(d*d*d)*.01;vy-=gravity*1000*y/(d*d*d)*.01;x+=vx*.01;y+=vy*.01;}return {x,y};}
function check(h,x,y,gravity=80,speed=100){const g=geometry(h),end=endpoint(x,y,gravity,speed);assert.ok(g.square);close(g.square.x+4,g.r.width/2+end.x*g.s);close(g.square.y+4,g.r.height/2+end.y*g.s);close(g.square.w,8);close(g.square.h,8);if(g.legend)assert.ok(!overlaps(g.square,g.legend),'the first-planet legend must leave the full endpoint stroke clear');return g;}
function model(h){const s=scale(h);return {bodies:h.drawing().filter(c=>c[0]==='arc'&&Math.abs(c[3]*s-4.5)<1e-8).map(c=>c.slice(1,3)),metrics:h.el('metrics').textContent,point:h.el('orbit-position-current').textContent,preview:h.el('orbit-preview-reading').textContent,measurement:h.el('orbit-measured-reading').textContent,recall:h.el('orbit-recall-status').textContent,url:location.href,notes:h.el('notes-text').value};}

test('public 767 × 317.9375 reproduction exposes the endpoint at (-500, -35)',async()=>{const h=await setup('?experiment=orbit');h.resize(767,317.9375);position(h,-500,-35);const g=check(h,-500,-35);assert.ok(g.square.x+4>51&&g.square.x+4<52);assert.ok(g.square.y+4>48&&g.square.y+4<49);close(g.legend.y,317.9375-85);assert.equal(h.el('metrics').textContent,'3 颗行星 · t + 0.0 s');assert.match(h.el('orbit-preview-reading').textContent,/x -475.5，y -158.6/);});

test('ordinary target retains original upper legend and preview geometry',async()=>{const h=await setup('?experiment=orbit'),g=check(h,140,0);close(g.legend.x,8);close(g.legend.y,38);close(g.legend.w,196);close(g.legend.h,23);const before=h.drawing();h.resize(600,414);assert.deepEqual(h.drawing(),before);});

test('first-planet legend clears nearby endpoint positions and changed launch parameters',async()=>{const h=await setup('?experiment=orbit');h.resize(767,317.9375);let moved=0,ordinary=0;for(const x of [-520,-500,-480])for(const y of [-55,-35,-15])for(const speed of [65,100,150]){h.el('speed').handlers.input({target:{value:String(speed)}});position(h,x,y);const g=check(h,x,y,80,speed);if(g.legend?.y>38)moved++;else ordinary++;}assert.ok(moved>0&&ordinary>0);for(const gravity of [30,160]){h.el('gravity').handlers.input({target:{value:String(gravity)}});position(h,-500,-35);check(h,-500,-35,gravity,150);}});

test('fractional sizes and display density preserve exact model and endpoint clearance',async()=>{const h=await setup('?experiment=orbit');position(h,-500,-35);const before=model(h),announcement=h.el('announcement').textContent;for(const [w,v] of [[171,240],[259,240],[334.5,281.75],[600,414],[767,317.9375],[1200,560]])for(const dpr of [1,1.25,2,3]){h.resize(w,v);h.setDpr(dpr);check(h,-500,-35);assert.deepEqual(model(h),before);assert.equal(h.el('announcement').textContent,announcement);}});

test('collision includes endpoint stroke edges and checks the lower fallback too',()=>{
 const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');const fn=source.slice(source.indexOf('function drawOrbitMeasurementLegend('),source.indexOf('// Label the actual model-to-screen scale'));
 function draw(ex,ey,{height=318,launcher={x:300,y:200},prediction=true,paused=true}={}){const commands=[],ctx=new Proxy({}, {get:(_,key)=>(...args)=>commands.push([key,...args]),set:(_,key,value)=>(commands.push([key,value]),true)});const body={x:300,y:100,vx:0,vy:1};let predictions=0;new Function('width','height','paused','bodies','orbitPoint','ctx','orbitMeasuredBodyVisible','orbitPrediction',fn+';drawOrbitMeasurementLegend(1);')(767,height,paused,[body],launcher,ctx,()=>true,()=>{predictions++;return prediction?{end:{x:ex-767/2,y:ey-height/2}}:null;});return {commands,predictions,panel:commands.find(c=>c[0]==='fillRect')};}
 for(const [x,y,relocated] of [[3.25,49,true],[208.75,49,true],[100,33.25,true],[100,65.75,true],[3.24,49,false],[208.76,49,false],[100,33.24,false],[100,65.76,false]]){const g=draw(x,y);assert.ok(g.panel);close(g.panel[2]+159,relocated?233:38);assert.equal(g.predictions,1,'one prediction supplies both offset and collision');}
 // Force upper-corner conflict, then put the endpoint in the lower fallback.
 assert.equal(draw(100,244,{launcher:{x:100-383.5,y:49-159}}).panel,undefined);assert.equal(draw(100,49,{height:110}).panel,undefined);close(draw(100,20,{prediction:false,paused:false}).panel[2]+159,9);
});

test('running, pause, stepping and recall keep physics and all endpoint geometry',async()=>{const h=await setup('?experiment=orbit');h.resize(767,317.9375);position(h,-500,-35);click(h,'orbit-fire');const before=model(h);check(h,-500,-35);click(h,'pause');assert.equal(geometry(h).square,undefined);assert.equal(h.frames.size,1);h.tick(0);h.tick(50);click(h,'pause');check(h,-500,-35);assert.notDeepEqual(model(h).bodies,before.bodies);const time=h.el('metrics').textContent;click(h,'orbit-recall');check(h,-500,-35);assert.equal(h.el('metrics').textContent,time.replace('4 颗','3 颗'));click(h,'step');check(h,-500,-35);assert.equal(h.frames.size,0);});

test('body limit and invalid center retain measurement legend without a prediction',async()=>{const h=await setup('?experiment=orbit');position(h,0,0);assert.equal(geometry(h).square,undefined);assert.ok(geometry(h).legend);click(h,'orbit-home');for(let i=0;i<21;i++)click(h,'orbit-fire');assert.equal(geometry(h).square,undefined);assert.equal(h.el('orbit-preview-reading').hidden,true);assert.ok(geometry(h).legend);click(h,'orbit-recall');check(h,140,0);click(h,'reset');check(h,140,0);});

test('focus, context, visibility and retained worlds preserve relocated legend and feedback',async()=>{const h=await setup('?experiment=orbit');h.resize(767,317.9375);position(h,-500,-35);const before=model(h),drawing=h.drawing(),announcement=h.el('announcement').textContent;h.el('orbit-position-apply').focus();h.el('canvas').handlers.focus();h.el('canvas').handlers.blur();h.loseContext();h.restoreContext();h.setHidden(true);h.setHidden(false);h.setVisible(false);h.setVisible(true);assert.deepEqual(model(h),before);assert.deepEqual(h.drawing(),drawing);assert.equal(h.el('announcement').textContent,announcement);assert.equal(document.activeElement,h.el('orbit-position-apply'));for(const world of ['life','wave','fractal','walk']){click(h,'tab-'+world);click(h,'tab-orbit');check(h,-500,-35);assert.deepEqual(model(h),before);}});

test('snapshot requests include corrected overlay while sharing keeps the target',async()=>{const h=await setup('?experiment=orbit');h.resize(767,317.9375);position(h,-500,-35);const before=model(h);let captured;h.el('canvas').toBlob=callback=>{captured=h.drawing();callback(null);};click(h,'save');assert.deepEqual(captured,h.drawing());await click(h,'share');check(h,-500,-35);assert.deepEqual(model(h),before);assert.equal(new URL(h.el('share-link').value).searchParams.has('at'),false);});

test('Orbit discovery and intentional Fractal/Walk primary batch repeats remain unchanged',async()=>{const h=await setup('?experiment=orbit');click(h,'mission-start');click(h,'mission-check');h.el('gravity').handlers.input({target:{value:'40'}});for(let i=0;i<80;i++)click(h,'step');click(h,'mission-check');assert.equal(h.el('notes-count').textContent,'1 / 5');const notes=h.el('notes-text').value;position(h,-500,-35);check(h,-500,-35,40);assert.equal(h.el('notes-text').value,notes);for(const [world,expected] of [['fractal',/500 个点/],['walk',/48 步/]]){click(h,'tab-'+world);for(const repeat of [false,true]){h.el('step').handlers.keydown({key:'Enter',repeat,preventDefault(){assert.fail('intentional batch repeat suppressed');}});click(h,'step');}assert.match(h.el('metrics').textContent,expected);}assert.equal(h.el('notes-text').value,notes);});

test('fresh page requests the endpoint-safe legend application',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/app\.js\?[^"\n]*&amp;legend-endpoint=clear-1/);});
