import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup} from './life-challenge-harness.js';
const click=(h,id)=>h.el(id).handlers.click();
const fit=h=>click(h,'orbit-preview-fit');
const available=h=>h.el('orbit-preview-fit').getAttribute('aria-disabled')==='false';
const scale=h=>h.drawing().find(c=>c[0]==='scale')?.[1];
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ≈ ${b}`);
function position(h,x,y){h.el('orbit-target-x').value=String(x);h.el('orbit-target-y').value=String(y);click(h,'orbit-position-apply');}
function parameter(h,id,value){h.el(id).handlers.input({target:{value:String(value)}});}
// Independently integrate the stated softened model, sampling every fifth step.
function preview(x=140,y=0,g=160,s=150){const r=Math.hypot(x,y),v=Math.sqrt(g*1000/r)*s/100;let vx=-y/r*v,vy=x/r*v;const points=[[x,y]];for(let i=1;i<=1000;i++){const d=Math.max(Math.hypot(x,y),18);vx-=g*1000*x/d**3*.01;vy-=g*1000*y/d**3*.01;x+=vx*.01;y+=vy*.01;if(i%5===0)points.push([x,y]);}return points;}
function model(h){const d=h.drawing(),s=scale(h),trails=[];for(let i=0;i<d.length;i++)if(d[i][0]==='strokeStyle'&&/^#[a-f0-9]{6}75$/.test(d[i][1])){const end=d.findIndex((c,j)=>j>i&&c[0]==='stroke');trails.push(d.slice(i,end+1).filter(c=>['moveTo','lineTo'].includes(c[0])));}return {bodies:d.filter(c=>c[0]==='arc'&&Math.abs(c[3]*s-4.5)<1e-8).map(c=>c.slice(1,3)),trails};}
const fixed=h=>({model:model(h),metrics:h.el('metrics').textContent,position:h.el('orbit-position-current').textContent,preview:h.el('orbit-preview-reading').textContent,speed:h.el('orbit-speed').textContent,recall:h.el('orbit-recall-status').textContent,status:h.el('status').textContent,frames:[...h.frames.keys()],url:location.href,writes:h.writes(),link:h.el('share-link').value,notes:h.el('notes-text').value,mission:h.el('mission-result').textContent,drafts:['orbit-target-x','orbit-target-y'].map(id=>h.el(id).value),error:h.el('orbit-position-error').textContent});
const state=h=>({fixed:fixed(h),drawing:h.drawing(),draws:h.drawCount(),message:h.el('announcement').textContent});
function inside(h,points,w=767,z=317.9375){const s=scale(h);for(const [x,y]of points){assert.ok(Math.abs(x)*s<=w/2-34+1e-8);assert.ok(Math.abs(y)*s<=z/2-34+1e-8);}const sq=h.drawing().find(c=>c[0]==='strokeRect'),end=points.at(-1);near(sq[1]+4/s,end[0]);near(sq[2]+4/s,end[1]);}
async function ready(){const h=await setup('?experiment=orbit&gravity=160&speed=150');h.resize(767,317.9375);return h;}

test('the public clipped preview fits all 201 exact samples without touching the simulation',async()=>{const h=await ready(),points=preview(),old=scale(h);assert.ok(points.at(-1)[1]*old>317.9375/2);assert.equal(available(h),true);assert.equal(h.el('orbit-fit').getAttribute('aria-disabled'),'true');h.el('orbit-preview-fit').focus();const before=fixed(h);fit(h);assert.deepEqual(fixed(h),before);assert.ok(scale(h)<old);inside(h,points);assert.equal(available(h),false);assert.equal(document.activeElement,h.el('orbit-preview-fit'));assert.match(h.el('announcement').textContent,/完整的 10 秒预演.*时间保持不变/);const after=state(h);fit(h);assert.deepEqual(state(h),after);});

test('an interior path excursion is considered even when its endpoint is inside',()=>{const source=readFileSync(new URL('../app.js',import.meta.url),'utf8'),fn=source.slice(source.indexOf('function orbitPreviewFitBounds('),source.indexOf("$('#orbit-preview-fit').addEventListener"));const check=(points,view=null,mode='orbit')=>new Function('mode','width','height','orbitScale','orbitView','orbitPoint',fn+';return orbitPreviewFitBounds(arguments[6]);')(mode,600,414,()=>1,view,{x:140,y:0},{points,end:{x:0,y:0}});assert.deepEqual(check([[140,0],[310,-400],[0,0]]),{x:310,y:400});assert.deepEqual(check([[140,0],[310,-400],[0,0]],{x:900,y:700}),{x:900,y:700});assert.equal(check([[140,0],[292,199],[0,0]]),null);assert.deepEqual(check([[140,0],[292.001,199],[0,0]]),{x:292.001,y:199});assert.equal(check([[140,0],[NaN,400]]),null);assert.equal(check([[140,0],[400,400]],null,'life'),null);});

test('both axes, fractional and narrow layouts fit the current gravity, speed and launcher',async()=>{const h=await ready();for(const [x,y,g,v,w,z]of [[140,0,160,150,171,240],[0,140,160,150,259,240],[-140,0,80,150,334.5,281.75],[22,0,160,150,767,317.9375],[140,-60,30,150,195,240]]){click(h,'reset');parameter(h,'gravity',g);parameter(h,'speed',v);position(h,x,y);h.resize(w,z);const before=fixed(h),p=preview(x,y,g,v);if(available(h)){fit(h);assert.deepEqual(fixed(h),before);inside(h,p,w,z);}else{const old=state(h);fit(h);assert.deepEqual(state(h),old);}}});

test('running, already visible, invalid launch and full capacity are quiet no-ops',async()=>{const h=await setup('?experiment=orbit');assert.equal(available(h),false);let before=state(h);fit(h);assert.deepEqual(state(h),before);parameter(h,'gravity',160);parameter(h,'speed',150);h.resize(767,317.9375);click(h,'pause');assert.equal(available(h),false);before=state(h);fit(h);assert.deepEqual(state(h),before);click(h,'pause');position(h,0,0);assert.equal(available(h),false);before=state(h);fit(h);assert.deepEqual(state(h),before);click(h,'orbit-home');for(let i=0;i<21;i++)click(h,'orbit-fire');assert.equal(available(h),false);before=state(h);fit(h);assert.deepEqual(state(h),before);click(h,'orbit-recall');assert.equal(available(h),true);fit(h);inside(h,preview());});

test('fit retains launched bodies, recall eligibility, trails and the exact next integration',async()=>{const control=await ready();click(control,'orbit-fire');for(let i=0;i<7;i++)click(control,'step');const expected=model(control),metrics=control.el('metrics').textContent;const h=await ready();click(h,'orbit-fire');for(let i=0;i<6;i++)click(h,'step');const before=fixed(h);fit(h);assert.deepEqual(fixed(h),before);click(h,'step');assert.deepEqual(model(h),expected);assert.equal(h.el('metrics').textContent,metrics);const s=scale(h);click(h,'orbit-recall');assert.equal(model(h).bodies.length,3);assert.equal(scale(h),s);});

test('held Enter is blocked while fresh Enter, Space, modifiers and IME keys retain native handling',async()=>{const h=await ready(),el=h.el('orbit-preview-fit');for(const e of [{key:'Enter',repeat:false},{key:' ',repeat:true},{key:'Tab',repeat:true},{key:'ArrowRight',repeat:true},{key:'x',repeat:true,isComposing:true}])el.handlers.keydown({...e,preventDefault(){assert.fail('unexpected key suppression');}});let prevented=false;el.handlers.keydown({key:'Enter',repeat:true,preventDefault(){prevented=true;}});assert.equal(prevented,true);const before=fixed(h);fit(h);assert.deepEqual(fixed(h),before);});

test('drafts, validation, sharing and an asynchronous copy remain independent of fitting',async()=>{const h=await ready();position(h,'unfinished','1e+');assert.equal(h.el('orbit-position-error').hidden,false);const before=fixed(h);fit(h);assert.deepEqual(fixed(h),before);click(h,'orbit-home');let resolve;Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:()=>new Promise(r=>resolve=r)}}});try{const pending=click(h,'share');const captured=h.el('share-link').value,before=fixed(h);fit(h);assert.deepEqual(fixed(h),before);const message=h.el('announcement').textContent;resolve();await pending;assert.equal(h.el('announcement').textContent,message);assert.equal(h.el('share-link').value,captured);assert.equal(new URL(captured).searchParams.has('at'),false);}finally{delete globalThis.navigator;}});

test('retained worlds, hash navigation and a real parameter navigation preserve their boundaries',async()=>{const h=await ready();fit(h);const s=scale(h),original=model(h);for(const world of ['life','wave','fractal','walk']){click(h,'tab-'+world);const other=state(h);fit(h);assert.deepEqual(state(h),other);click(h,'tab-orbit');assert.equal(scale(h),s);assert.deepEqual(model(h),original);}const before=state(h);h.navigate(location.search+'#canvas');const anchored=state(h);anchored.fixed.url=before.fixed.url;assert.deepEqual(anchored,before);h.navigate('?experiment=orbit&gravity=160&speed=150');assert.equal(available(h),false,'same parameters retain camera');h.navigate('?experiment=orbit&gravity=80&speed=150');assert.equal(available(h),true);fit(h);inside(h,preview(140,0,80,150));});

test('reflow, density and context recovery keep the fitted view; invalid dimensions refuse it',async()=>{const h=await ready();for(const [w,z]of [[0,414],[600,0],[68,414],[600,68],[NaN,414],[Infinity,414]]){h.resize(w,z);assert.equal(available(h),false);const before=state(h);fit(h);assert.deepEqual(state(h),before);}h.resize(767,317.9375);fit(h);const before=fixed(h);h.setDpr(2);h.loseContext();h.restoreContext();assert.deepEqual(fixed(h),before);inside(h,preview());h.resize(171,240);inside(h,preview(),171,240);h.setVisible(false);h.setHidden(true);h.setHidden(false);h.setVisible(true);assert.equal(h.frames.size,0);});

test('text-only startup may prepare a view and recovery shows the unchanged preview',async()=>{const h=await setup('?experiment=orbit&gravity=160&speed=150','',true,1,false);h.resize(767,317.9375);assert.equal(available(h),true);const metrics=h.el('metrics').textContent,reading=h.el('orbit-preview-reading').textContent;fit(h);assert.equal(h.el('metrics').textContent,metrics);assert.equal(h.el('orbit-preview-reading').textContent,reading);h.setContextReady(true);click(h,'canvas-retry');inside(h,preview());});

test('fitted previews neither record discoveries nor replace existing field notes or captures',async()=>{const h=await ready();click(h,'mission-start');click(h,'mission-check');parameter(h,'gravity',40);for(let n=0;n<80;n++)click(h,'step');click(h,'mission-check');assert.equal(h.el('notes-count').textContent,'1 / 5');const notes=h.el('notes-text').value;parameter(h,'gravity',160);parameter(h,'speed',150);fit(h);assert.equal(h.el('notes-text').value,notes);let captured;h.el('canvas').toBlob=cb=>{captured=h.drawing();cb(null);};click(h,'save');assert.deepEqual(captured,h.drawing());for(const world of ['fractal','walk']){click(h,'tab-'+world);for(const repeat of [false,true]){h.el('step').handlers.keydown({key:'Enter',repeat,preventDefault(){assert.fail('intentional batch repetition changed');}});click(h,'step');}assert.match(h.el('metrics').textContent,world==='fractal'?/500 个点/:/48 步/);}assert.equal(h.el('notes-text').value,notes);});

test('availability repairs external attribute changes but idle redraws do not rewrite it',async()=>{const h=await ready(),e=h.el('orbit-preview-fit');let writes=0;const set=e.setAttribute.bind(e);e.setAttribute=(...a)=>{writes++;set(...a);};for(let n=0;n<120;n++)h.resize(767,317.9375);assert.equal(writes,0);e.attributes['aria-disabled']='wrong';h.resize(767,317.9375);assert.equal(writes,1);fit(h);assert.equal(writes,2);});

test('the native control has quiet context, wrapping 44px targets, dark focus and refreshed assets',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=readFileSync(new URL('../style.css',import.meta.url),'utf8');assert.match(html,/<button id="orbit-preview-fit" type="button" aria-controls="canvas" aria-disabled="true" aria-describedby="orbit-preview-fit-help">收进完整预演 ↗<\/button>/);assert.equal((html.match(/id="orbit-preview-fit"/g)||[]).length,1);assert.match(html,/<small id="orbit-preview-fit-help">暂停后.*不发射.*归位会把发射点移回 \(140, 0\)/);assert.match(css,/\.orbit-touch \.orbit-actions\{[^}]*flex-wrap:wrap/);assert.match(css,/\.orbit-touch \.orbit-actions button\{[^}]*white-space:normal;overflow-wrap:anywhere/);assert.match(css,/\.orbit-touch button\{[^}]*min-height:44px/);assert.match(css,/\.orbit-touch #orbit-preview-fit\[aria-disabled="true"\][^}]*background:#8b9d85/);assert.match(css,/\.stage,\.instrument-drawer\{--focus-ring:var\(--focus-on-dark\)\}/);for(const name of ['app.js','style.css'])assert.ok(html.match(new RegExp(name.replace('.','\\.')+'\\?[^"\\n]*&amp;preview-fit=whole-path-1')));});
