import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup} from './life-challenge-harness.js';
const click=(h,id)=>h.el(id).handlers.click();
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ≈ ${b}`);
function position(h,x,y){for(const [axis,value] of [['x',x],['y',y]]){h.el('orbit-target-'+axis).value=String(value);h.el('orbit-target-'+axis).handlers.input();}click(h,'orbit-position-apply');}
// Independently integrate the same stated softened model, never reading the
// production preview or its cache to obtain the expected destination.
function endpoint(x,y,gravity=80,speed=100){const r=Math.hypot(x,y),v=Math.sqrt(gravity*1000/r)*speed/100;let vx=-y/r*v,vy=x/r*v;for(let n=0;n<1000;n++){const d=Math.max(Math.hypot(x,y),18);vx-=gravity*1000*x/d**3*.01;vy-=gravity*1000*y/d**3*.01;x+=vx*.01;y+=vy*.01;}return {x,y};}
const overlaps=(a,b)=>a.x+a.w+.75>=b.x&&a.x-.75<=b.x+b.w&&a.y+a.h+.75>=b.y&&a.y-.75<=b.y+b.h;
function geometry(h){const ops=h.drawing(),s=ops.find(c=>c[0]==='scale')?.[1],r=h.el('canvas').getBoundingClientRect(),rect=c=>c&&({x:r.width/2+c[1]*s,y:r.height/2+c[2]*s,w:c[3]*s,h:c[4]*s});return {s,r,ops,square:rect(ops.find(c=>c[0]==='strokeRect')),panel:rect(ops.find(c=>c[0]==='fillRect'&&Math.abs(c[3]*s-132)<1e-8&&Math.abs(c[4]*s-46)<1e-8))};}
function check(h,x,y,gravity=80,speed=100){const g=geometry(h),end=endpoint(x,y,gravity,speed);assert.ok(g.square);near(g.square.x+4,g.r.width/2+end.x*g.s);near(g.square.y+4,g.r.height/2+end.y*g.s);near(g.square.w,8);near(g.square.h,8);if(g.panel){assert.ok(!overlaps(g.square,g.panel),'the full endpoint stroke must stay clear of the ruler');near(g.panel.w,132);near(g.panel.h,46);near(g.panel.y,g.r.height-56);assert.ok(g.panel.x>=16-1e-8&&g.panel.x+132<=g.r.width-16+1e-8);assert.match(h.el('orbit-scale-reading').textContent,new RegExp('^'+(Math.abs(g.panel.x-16)<1e-8?'左下':'右下')+'标尺：'));}else assert.match(h.el('orbit-scale-reading').textContent,/^标尺暂隐以留出画面；同心圆半径/);return g;}
function model(h){const g=geometry(h);return {bodies:g.ops.filter(c=>c[0]==='arc'&&Math.abs(c[3]*g.s-4.5)<1e-8).map(c=>c.slice(1,3)),metrics:h.el('metrics').textContent,point:h.el('orbit-position-current').textContent,preview:h.el('orbit-preview-reading').textContent,measurement:h.el('orbit-measured-reading').textContent,recall:h.el('orbit-recall-status').textContent,url:location.href,notes:h.el('notes-text').value};}
function isolated(ex,ey,width=647,height=317.9375,prediction=true){const source=readFileSync(new URL('../app.js',import.meta.url),'utf8'),fn=source.slice(source.indexOf('function drawOrbitScale('),source.indexOf('function drawOrbitLauncher('));const commands=[],reading={textContent:''},ctx=new Proxy({}, {get:(_,key)=>(...args)=>commands.push([key,...args]),set:(_,key,value)=>(commands.push([key,value]),true)});let calls=0;new Function('width','height','ctx','orbitPrediction','$','setReadingText',fn+';drawOrbitScale(1);')(width,height,ctx,()=>{calls++;return prediction?{end:{x:ex-width/2,y:ey-height/2}}:null;},()=>reading,(el,text)=>el.textContent=text);const plate=commands.find(c=>c[0]==='fillRect');return {commands,reading:reading.textContent,calls,panel:plate&&{x:plate[1]+width/2,y:plate[2]+height/2,w:plate[3],h:plate[4]}};}

test('public distant target exposes the exact endpoint by moving only the ruler to the right',async()=>{const h=await setup('?experiment=orbit');h.resize(647,317.9375);position(h,-1000,600);const g=check(h,-1000,600);assert.ok(g.square.x>102.87&&g.square.x<102.88);assert.ok(g.square.y>264.84&&g.square.y<264.85);near(g.panel.x,499);assert.match(h.el('orbit-scale-reading').textContent,/^右下标尺：200 模型单位/);assert.equal(h.el('metrics').textContent,'3 颗行星 · t + 0.0 s');assert.equal(h.el('notes-count').textContent,'0 / 5');});

test('stroke-edge contacts relocate while just-clear positions keep the original ruler',()=>{for(const [x,y,moved] of [[11.25,280,true],[152.75,280,true],[100,257.1875,true],[100,312.6875,true],[11.249,280,false],[152.751,280,false],[100,257.1865,false],[100,312.6885,false]]){const g=isolated(x,y);near(g.panel.x,moved?499:16);assert.equal(g.calls,1);near(g.panel.y,261.9375);}assert.equal(isolated(100,200,171,240).panel,undefined);assert.equal(isolated(100,200,163,240,false).panel,undefined);near(isolated(100,200,164,240,false).panel.x,16);near(isolated(100,200,647,318,false).panel.x,16);});

test('relocation retains font, backing, scale interval, tick lengths and paint order',()=>{const a=isolated(100,280),b=isolated(400,100),normalize=g=>g.commands.map(c=>['fillText','fillRect','moveTo','lineTo'].includes(c[0])?[c[0],...c.slice(1).map((v,i)=>typeof v==='number'&&i===(c[0]==='fillText'?1:0)?v-(g.panel.x-16):v)]:c);assert.deepEqual(normalize(a),normalize(b));assert.ok(a.commands.some(c=>c[0]==='font'&&c[1]==='11px sans-serif'));assert.equal(a.commands.at(-1)[0],'restore');});

test('narrow, fractional, density and context redraws keep the same exact destination and model',async()=>{const h=await setup('?experiment=orbit');position(h,-1000,600);const before=model(h),message=h.el('announcement').textContent;for(const [w,z] of [[171,240],[259,240],[334.5,281.75],[647,317.9375],[1200,560]])for(const dpr of [1,1.25,2,3]){h.resize(w,z);h.setDpr(dpr);check(h,-1000,600);assert.deepEqual(model(h),before);assert.equal(h.el('announcement').textContent,message);}h.loseContext();h.restoreContext();check(h,-1000,600);assert.deepEqual(model(h),before);});

test('nearby targets, speed and gravity changes preserve exact prediction at every ruler placement',async()=>{const h=await setup('?experiment=orbit');h.resize(647,317.9375);let right=0,left=0;for(const x of [-1500,-1000,-700,140])for(const y of [0,400,600,900])for(const speed of [30,100,150]){h.el('speed').handlers.input({target:{value:String(speed)}});position(h,x,y);const g=check(h,x,y,80,speed);if(g.panel?.x>16.1)right++;else left++;}assert.ok(right>0&&left>0);for(const gravity of [30,160]){h.el('gravity').handlers.input({target:{value:String(gravity)}});position(h,-1000,600);check(h,-1000,600,gravity,150);}});

test('pause, running, stepping and recall preserve integration and restore ruler placement',async()=>{const h=await setup('?experiment=orbit');h.resize(647,317.9375);position(h,-1000,600);click(h,'orbit-fire');const before=model(h);click(h,'pause');assert.equal(geometry(h).square,undefined);near(geometry(h).panel.x,16);h.tick(0);h.tick(50);click(h,'pause');check(h,-1000,600);assert.notDeepEqual(model(h).bodies,before.bodies);const time=h.el('metrics').textContent;click(h,'orbit-recall');check(h,-1000,600);assert.equal(h.el('metrics').textContent,time.replace('4 颗','3 颗'));click(h,'step');check(h,-1000,600);assert.equal(h.frames.size,0);});

test('Home, invalid center, body cap, presets and history retain their existing effects',async()=>{const h=await setup('?experiment=orbit');h.resize(647,317.9375);position(h,-1000,600);h.key('Home');check(h,140,0);near(geometry(h).panel.x,16);position(h,0,0);assert.equal(geometry(h).square,undefined);near(geometry(h).panel.x,16);click(h,'orbit-home');for(let n=0;n<21;n++)click(h,'orbit-fire');assert.equal(geometry(h).square,undefined);near(geometry(h).panel.x,16);click(h,'orbit-recall');check(h,140,0);click(h,'reset');check(h,140,0);h.el('preset-select').handlers.change({target:{value:'elliptic'}});click(h,'load-preset');check(h,140,0,80,100);h.navigate('?experiment=orbit&gravity=40&speed=30');check(h,140,0,40,30);});

test('fixed reading nodes, focus, visibility and retained worlds stay unchanged on repeated redraws',async()=>{const h=await setup('?experiment=orbit');h.resize(647,317.9375);position(h,-1000,600);const el=h.el('orbit-scale-reading');let text=el.textContent,writes=0;Object.defineProperty(el,'textContent',{get:()=>text,set:value=>{writes++;text=value;}});const before=model(h),drawing=h.drawing(),message=h.el('announcement').textContent;h.el('orbit-position-apply').focus();for(let n=0;n<120;n++)h.resize(647,317.9375);h.el('canvas').handlers.focus();h.el('canvas').handlers.blur();h.setVisible(false);h.setVisible(true);h.setHidden(true);h.setHidden(false);assert.equal(writes,0);assert.equal(document.activeElement,h.el('orbit-position-apply'));assert.deepEqual(h.drawing(),drawing);assert.equal(h.el('announcement').textContent,message);for(const world of ['life','wave','fractal','walk']){click(h,'tab-'+world);click(h,'tab-orbit');check(h,-1000,600);assert.deepEqual(model(h),before);}});

test('text-only and collapsed geometry restore the selected target without fabricating a ruler',async()=>{const h=await setup('?experiment=orbit','',true,1,false);position(h,-1000,600);assert.equal(h.el('orbit-scale-reading').textContent,'');h.setContextReady(true);click(h,'canvas-retry');check(h,-1000,600);h.resize(0,0);assert.equal(h.el('orbit-scale-reading').textContent,'');h.resize(647,317.9375);check(h,-1000,600);});

test('capture requests, parameter-only sharing, discoveries and intentional batches retain behavior',async()=>{const h=await setup('?experiment=orbit');click(h,'mission-start');click(h,'mission-check');h.el('gravity').handlers.input({target:{value:'40'}});for(let n=0;n<80;n++)click(h,'step');click(h,'mission-check');assert.equal(h.el('notes-count').textContent,'1 / 5');const notes=h.el('notes-text').value;h.resize(647,317.9375);position(h,-1000,600);check(h,-1000,600,40);const before=model(h);let captured;h.el('canvas').toBlob=f=>{captured=h.drawing();f(null);};click(h,'save');assert.deepEqual(captured,h.drawing());await click(h,'share');assert.deepEqual(model(h),before);assert.equal(new URL(h.el('share-link').value).searchParams.has('at'),false);for(const [world,expected] of [['fractal',/500 个点/],['walk',/48 步/]]){click(h,'tab-'+world);for(const repeat of [false,true]){h.el('step').handlers.keydown({key:'Enter',repeat,preventDefault(){assert.fail('batch repeat blocked');}});click(h,'step');}assert.match(h.el('metrics').textContent,expected);}assert.equal(h.el('notes-text').value,notes);});

test('fresh pages request the corrected script and the scale explanation stays quiet',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/app\.js\?[^"\n]*&amp;ruler-endpoint=clear-1/);assert.match(html,/<small id="orbit-scale-reading" aria-live="off"><\/small>/);});
