import test from 'node:test';import assert from 'node:assert/strict';import {lifeStep,orbitStep,waveValue} from '../simulations.js';
test('life empty universe stays empty',()=>assert.deepEqual(lifeStep(new Uint8Array(25),5,5),new Uint8Array(25)));
test('life block remains stable',()=>{const c=new Uint8Array(36);[14,15,20,21].forEach(i=>c[i]=1);assert.deepEqual(lifeStep(c,6,6),c);});
test('life blinker returns after two generations',()=>{const c=new Uint8Array(25);[11,12,13].forEach(i=>c[i]=1);const n=lifeStep(c,5,5);assert.deepEqual([...n.entries()].filter(([i,v])=>v).map(([i])=>i),[7,12,17]);assert.deepEqual(lifeStep(n,5,5),c);});
test('life toroidal boundary wraps',()=>{const c=new Uint8Array(25);[10,14,11].forEach(i=>c[i]=1);const n=lifeStep(c,5,5);assert.equal(n[5],1);assert.equal(n[10],1);assert.equal(n[15],1);});
test('orbit remains bounded near circular orbit',()=>{const b={x:100,y:0,vx:0,vy:Math.sqrt(80000/100)};for(let i=0;i<10000;i++)orbitStep(b,80000,.005);assert.ok(Math.abs(Math.hypot(b.x,b.y)-100)<.3);});
test('orbit origin is finite',()=>{const b=orbitStep({x:0,y:0,vx:0,vy:0},80000,.1);assert.ok(Number.isFinite(b.x)&&Number.isFinite(b.y));});
test('waves are symmetric and bounded',()=>{for(let x=-100;x<100;x+=4)for(let y=-100;y<100;y+=4){const a=waveValue(x,y,1,80,32);assert.ok(Math.abs(a)<=1);assert.ok(Math.abs(a-waveValue(-x,y,1,80,32))<1e-10);}});
import {parseSettings,serializeSettings} from '../simulations.js';
const config={orbit:{sliders:[['gravity','g',30,160,80],['speed','s',30,150,100]]},life:{sliders:[['rate','r',1,20,8]]}};
test('URL settings round trip',()=>{const state=parseSettings('?'+serializeSettings('orbit',{gravity:120,speed:70}),config);assert.deepEqual(state,{mode:'orbit',values:{gravity:120,speed:70}});});
test('URL settings clamp untrusted values',()=>{assert.deepEqual(parseSettings('?experiment=orbit&gravity=9000&speed=NaN',config),{mode:'orbit',values:{gravity:160,speed:100}});});
test('URL unknown mode falls back safely',()=>{assert.equal(parseSettings('?experiment=unknown',config).mode,'orbit');});
import {population,repeatPeriod,wavePathDifference} from '../simulations.js';
test('population and exact-state period detection',()=>{const c=Uint8Array.from([0,1,1,0]);assert.equal(population(c),2);assert.equal(repeatPeriod([{generation:2,key:'0110'}],c,4),2);assert.equal(repeatPeriod([{generation:4,key:'0110'}],c,4),null);assert.equal(repeatPeriod([{generation:2,key:'1001'}],c,4),null);});
test('wave central axis constructive',()=>{const p=wavePathDifference(0,80,100,32);assert.equal(p.difference,0);assert.equal(p.kind,'constructive');assert.equal(p.envelope,1);});
test('wave half wavelength cancels',()=>{const p=wavePathDifference(8,0,100,32);assert.equal(p.cycles,.5);assert.equal(p.kind,'destructive');assert.ok(p.envelope<1e-10);});
